from src.jp_prefectures_simple.prefs import code2name


def test_code_int():
    assert code2name(1) == "北海道"
    assert code2name(2) == "青森県"
    assert code2name(3) == "岩手県"
    assert code2name(4) == "宮城県"
    assert code2name(5) == "秋田県"
    assert code2name(6) == "山形県"
    assert code2name(7) == "福島県"
    assert code2name(8) == "茨城県"
    assert code2name(9) == "栃木県"
    assert code2name(10) == "群馬県"
    assert code2name(11) == "埼玉県"
    assert code2name(12) == "千葉県"
    assert code2name(13) == "東京都"
    assert code2name(14) == "神奈川県"
    assert code2name(15) == "新潟県"
    assert code2name(16) == "富山県"
    assert code2name(17) == "石川県"
    assert code2name(18) == "福井県"
    assert code2name(19) == "山梨県"
    assert code2name(20) == "長野県"
    assert code2name(21) == "岐阜県"
    assert code2name(22) == "静岡県"
    assert code2name(23) == "愛知県"
    assert code2name(24) == "三重県"
    assert code2name(25) == "滋賀県"
    assert code2name(26) == "京都府"
    assert code2name(27) == "大阪府"
    assert code2name(28) == "兵庫県"
    assert code2name(29) == "奈良県"
    assert code2name(30) == "和歌山県"
    assert code2name(31) == "鳥取県"
    assert code2name(32) == "島根県"
    assert code2name(33) == "岡山県"
    assert code2name(34) == "広島県"
    assert code2name(35) == "山口県"
    assert code2name(36) == "徳島県"
    assert code2name(37) == "香川県"
    assert code2name(38) == "愛媛県"
    assert code2name(39) == "高知県"
    assert code2name(40) == "福岡県"
    assert code2name(41) == "佐賀県"
    assert code2name(42) == "長崎県"
    assert code2name(43) == "熊本県"
    assert code2name(44) == "大分県"
    assert code2name(45) == "宮崎県"
    assert code2name(46) == "鹿児島県"
    assert code2name(47) == "沖縄県"


if __name__ == "__main__":
    test_code_int()
