"""Tests for name2code function with string input."""
from src.jp_prefectures_simple import name2code



def test_name():
    """Test converting prefecture names to codes."""

    assert name2code("北海道") == "01"
    assert name2code("青森県") == "02"
    assert name2code("岩手県") == "03"
    assert name2code("宮城県") == "04"
    assert name2code("秋田県") == "05"
    assert name2code("山形県") == "06"
    assert name2code("福島県") == "07"
    assert name2code("茨城県") == "08"
    assert name2code("栃木県") == "09"
    assert name2code("群馬県") == "10"
    assert name2code("埼玉県") == "11"
    assert name2code("千葉県") == "12"
    assert name2code("東京都") == "13"
    assert name2code("神奈川県") == "14"
    assert name2code("新潟県") == "15"
    assert name2code("富山県") == "16"
    assert name2code("石川県") == "17"
    assert name2code("福井県") == "18"
    assert name2code("山梨県") == "19"
    assert name2code("長野県") == "20"
    assert name2code("岐阜県") == "21"
    assert name2code("静岡県") == "22"
    assert name2code("愛知県") == "23"
    assert name2code("三重県") == "24"
    assert name2code("滋賀県") == "25"
    assert name2code("京都府") == "26"
    assert name2code("大阪府") == "27"
    assert name2code("兵庫県") == "28"
    assert name2code("奈良県") == "29"
    assert name2code("和歌山県") == "30"
    assert name2code("鳥取県") == "31"
    assert name2code("島根県") == "32"
    assert name2code("岡山県") == "33"
    assert name2code("広島県") == "34"
    assert name2code("山口県") == "35"
    assert name2code("徳島県") == "36"
    assert name2code("香川県") == "37"
    assert name2code("愛媛県") == "38"
    assert name2code("高知県") == "39"
    assert name2code("福岡県") == "40"
    assert name2code("佐賀県") == "41"
    assert name2code("長崎県") == "42"
    assert name2code("熊本県") == "43"
    assert name2code("大分県") == "44"
    assert name2code("宮崎県") == "45"
    assert name2code("鹿児島県") == "46"
    assert name2code("沖縄県") == "47"


if __name__ == "__main__":
    test_name()
